### ISSUE TITLE
Test homepage

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#21]
Some notes of things we want to test on the homepage:

- Years under the spark charts: 2003-2004, for example. Do users understand that this is Jan 2003 - Dec 2004?

**Comment by emileighoutlaw** [comment]
Oooooo! Can I add to this? I'd love to know what users think the word "compliance" means, although I don't know how best to test this (especially if the new homepage doesn't have compliance links in it)

**Comment by nickykrause** [comment]
revealed the following issues relevant to the homepage:
https://github.com/18F/fec-testing/issues/20
https://github.com/18F/fec-testing/issues/19
https://github.com/18F/fec-testing/issues/22
