### ISSUE TITLE
Gather feedback on legal resource search results display

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#26]
Designs + discussion appear in https://github.com/18F/openFEC-web-app/issues/1761.

**Comment by nickykrause** [comment]
There are five user sessions scheduled for next week. I will update this issue with more information about the findings once the sessions are finished.

**Comment by nickykrause** [comment]
### Research results:
(cc @jenniferthibault  - this is the same as what we went through earlier via video chat)

**Mixed reviews for `More Recent AOs citing this AO` column**
> When I'm looking at an AO, I do often look for other AOs that cite back to it, just to make sure that I’m exploring the whole universe of material...but, I wouldn’t have known until I saw this column in the search results that seeing that same information would be useful at this level, too, and for a totally different reason. It’s like you made something I didn’t even know I would have wanted or needed, but, now that I see it, I can see how helpful it’d be. 

> This is useful. The second one is a good example - the AO is from 1979. I might disregard that result, except that it says in the more `recent column` that there is a related AO from 2011. If I see that there’s one from 2011 that cited it, then suddenly that 1979 AO is more relevant to me. When I'm looking at an AO, I do often look for other AOs that cite back to it, just to make sure that I’m exploring the whole universe of material, but I wouldn’t have known until I saw this column in the search results that seeing that same information would be useful at this level, too, and for a totally different reason. It’s like you made something I didn’t even know I would have wanted or needed, but, now that I see it, I can see how helpful it’d be. 

> I’m not sure that I’d need that right at this level. I’d definitely want to know that once I open the the AO. Not sure if I’d use it here, but I don’t know what to show instead.

**Suggestion to rename the `More Recent AOs citing this AO` column**

> “More recent” AOs that cite this AO — why say “more recent”? if other AOs cite this AO, then they’re definitely more recent, so the fact that you’re calling out “More recent” makes me think they’re _especially_ recent, to the exclusion of other recent ones. 


**Praise for consistency of display across resource types**
> I like that these are all similar — I mean, they’re not exactly the same, because they’re different kinds of matters with different info — but they are as consistent as possible in terms of the display. It makes it easier to move between them and get a good sense of what’s there, even when I’m not as familiar with some of them.


**Praise for the display of the keyword hits**
> I like the amount of context that’s showing for the hits. This is a good amount of context, compared to the old site - it’s not like you are reading the whole doc, but enough to give you context.

> I think it’s really good. Especially the portion where you can see the text you’re searching for and why it’s popping up, where it appears. That’s a really helpful thing that we don’t have now.


**Praise for the display of pending AOs**
> I like the display for the one that’s pending. i like not just that it says pending, but that there is an hourglass that draws your attention.I love the link to the comment period - that’s really useful.

> It’s helpful to see this. Sometimes we won’t even proceed on a case until a pending AO has been decided, so it’s nice to incorporate them and call them out. 

**Mixed thoughts on Election Cycle column**
> Election cycle is fine - it’s a good proxy for how recent it was. Would be useful if the election cycle column would be sortable -- that’d be great. 
> [Would `Close date` be more helpful?]
> I’m not sure - someone in enforcement would know better. I’m not familiar enough with how they work to know if the close date is a better indicator than the Election Cycle. Regardless, it is useful to have a date, and a column that could be sorted by date, but the enforcement attorneys would be better to tell you what kind of date.

> I could see where both `Election Cycle` and `Close Date` would be helpful. Because sometimes cases are decided so long after an election cycle. Sometimes the close date can be more relevant. It might be easy to put all off that in this column somehow? With parentheses, like you did for Disposition?

> I think either one works. I think I would probably like to see the Election Cycle because that gives you the period that the activity took place, but that’s not a strong preference on my part.

**Sorting by date is essential**
> We try to look at recent stuff to get authority for stuff that is more recent now.

> Regardless of what the date indicator is, it is useful to have a date, and a column that could be sorted by date.

> When deciding between cases, I look at the most recent first. So, being able to arrange them in reverse chronological order is important.

**Expectation that “text search” is a way to search citations by doc; citation fields are a way to search citations by case (consistent with old system)**
> For my purposes, it would be most useful to see where in the document it is. If it’s in a footnote -it’s not really a focus of the analysis. But I could just do a text search for the citation, right? And it would show up in the document level? [Yes] So, that’d be fine for me.  And if you searched citations explicitly and it only came up at the case level - that’d be fine. Then you’d have both. The statutes and regs are always cited in the  same way in the docs, so it’s easy to do a text search.


**Curiosity (and some concern) about how many keyword snippets will show**

> A lot of the search words are very common in our reports, so some of the documents will have lots and lots of hits. It could get really long if you show them all. Maybe you could just show a few and then show the number of additional results? I’m not sure. But I just wonder how many hits it will show.

> [Asked another user about this after one user brought it up] I see the problem, but showing the snippets and keyword matches is very very helpful - I wouldn’t want to lose it. It’s very important to be able to distinguish the wheat from the chaff. Especially because the first thing that’s going to pop up probably is the first instance of that match in the doc — that’s often the least helpful text, it’s like pro forma stuff. So, it’d be helpful to be able to decide right here to show more or not. Like, show some of them  and then give me the option to show the rest, right here, so I don’t have to open the PDF.

**Comment by jenniferthibault** [comment]
@nickykrause great writeup as always :) I incorporated what we chatted about on the last point into the mockups in #1761, but not sure how I should interact with this issue. Should I put any mockups in here? Or is this mostly for documentation?

**Comment by nickykrause** [comment]
@jenniferthibault - Thanks! And yes, this is just documentation. We can close this issue now that the results have been reviewed, and any needed actions have been taken in a linked issue. 

Closing!
