### ISSUE TITLE
Do we need the search link in the candidate & committee services section?

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#32]
Test script:
https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-2-3-17.md

Issue summary:
- One user noted that the candidate/committee search in the candidate & committee services section seemed out of place. 

This is not enough data to act on yet, but it is an open question: Do we need that search bar? is it useful to people?

Related issue: https://github.com/18F/fec-cms/issues/766

**Comment by jenniferthibault** [comment]
@nickykrause do you know what search the person was referring to? I just went looking for it, but couldn't identify where this feedback applied

**Comment by nickykrause** [comment]
@jenniferthibault! This is old, actually - the design changed, and the search bar isn't there anymore! So, we can close.
