### ISSUE TITLE
Users experience a text-entry issue when typing into the AO regulatory citation search field

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#41]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-3-31-17-AOs.md), two separate users attempted to enter 116.11 into the `Regulatory citation` field and had the same text-entry issue: Specifically, when they started typing, the field did not seem to accept the leading 11, or, if it did, it very quickly overwrote those digits with the following 6. 

It was hard to tell what was happening, and I am not able to replicate the error myself, but both users found it disruptive and paused to say "Did you see that?" -- after which, they repeated the action, and were not able to clearly replicate the issue.

The users were testing on [this page](https://fec-dev-proxy.app.cloud.gov/data/legal/search/advisory-opinions/?api_key=&type=advisory_opinions&search=president&search_type=advisory_opinions&q=president).

They were entering data into this `regulatory citation` field:

![image](https://cloud.githubusercontent.com/assets/1450173/24817072/b59626fc-1ba0-11e7-82ae-d166b5570a65.png)

**Comment by patphongs** [comment]
This issue could not be replicated. Most likely already resolved this bug.
