### ISSUE TITLE
Users expect to be able to hit 'enter' to initiate searches using AO filters

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#43]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-3-31-17-AOs.md), all three of the users noted (without provocation) that they expected to be able to hit the `enter` key on their keyboards in order to activate their searches/filters when using the fields in the AO filter panel. (As compared to having to click the magnifying glass icons)

Screenshot for reference:
![image](https://cloud.githubusercontent.com/assets/1450173/24817754/6a1bda2a-1ba3-11e7-931e-0f842a733bd7.png)

**Comment by noahmanger** [comment]
This works now, so I'm closing.
