### ISSUE TITLE
Blue/green graph lines are too close in color

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#5]
**from test script:**
https://github.com/18F/FEC/blob/master/test_scripts/2016-08-18.md

**feature tested:** 
Campaign finance data landing page graphs

**original question:**
What is this graph telling you?
(Expected answers: comparing how much money different groups raised over time; party committees raising the most; total amount raised at certain points)

**synthesized answer:**
People on the whole understood the chart, though different users raised different concerns. One wanted a separate line for Super PACs, another wasn't sure if the data included all federal elections, another had trouble at first with the color of the graph lines but later figured it out.

**action:**
Discuss the observation that blue/green graph lines are close in color. Is this an issue?

**Comment by jenniferthibault** [comment]
Answer: yes :)

**Comment by nickykrause** [comment]
Possibly related: https://github.com/18F/FEC/issues/412

**Comment by nickykrause** [comment]
Addressed by: https://github.com/18F/fec-style/pull/630
