### ISSUE TITLE
Test findability and usability of the RAD form

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#53]
Here is the form in question:
https://beta.fec.gov/help-candidates-and-committees/question-rad/

We want to be sure that users are able to find this form and that they know how it works, including the feature that allows users to find their RAD analyst.

We hypothesize that users who are looking for the RAD contact form will know to look for it in the `Contact` section of the site.

**Comment by patphongs** [comment]
closing in favor of summarized issue #89
