### ISSUE TITLE
Add "federal" to "all elections" graph title to help clarify that this is only for fed elections

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#6]
**from test script:**
https://github.com/18F/FEC/blob/master/test_scripts/2016-08-18.md

**feature tested:** 
Campaign finance data landing page graphs

**original question:**

What is this graph telling you?
(Expected answers: comparing how much money different groups raised over time; party committees raising the most; total amount raised at certain points)

**synthesized answer:**
People on the whole understood the chart, though different users raised different concerns. One wanted a separate line for Super PACs, _another wasn't sure if the data included all federal elections,_ another had trouble at first with the color of the graph lines but later figured it out.

**action:**
Add "federal" to "all elections" title to help clarify that this is only for fed elections.

**Comment by emileighoutlaw** [comment]
Adding "federal" is an A+ content change, in my opinion.

**Comment by jenniferthibault** [comment]
@nickykrause I know this was from a while ago, but do you know where this applies, or if it still does? I'm not seeing the "all elections" copy on this page anymore:

<img width="1058" alt="screen shot 2017-04-19 at 10 29 44 pm" src="https://cloud.githubusercontent.com/assets/11636908/25210838/de406ce4-254f-11e7-90e1-f195cd0ea7e6.png">

**Comment by nickykrause** [comment]
Good point, @jenniferthibault -- I don't think it is relevant anymore! It would be easier to know for sure if I had included a screenshot in my original post. Lesson learned!
