### ISSUE TITLE
Can't click "search individual contributions" in site-wide search if hovering over text

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#61]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-05-12.md), when one user entered a person's name into the site-wide search and then tried to select `search individual contributions from: [name]` in the typeahead, nothing happened. It seemed like the button was not responding.

I am able to replicate this issue on my machine by searching for a name -- nothing happens when I try to click `search individual contributions...`:
<img width="292" alt="screen shot 2017-05-16 at 10 20 44 am" src="https://cloud.githubusercontent.com/assets/1450173/26113983/b87a8b7a-3a21-11e7-8213-f1c8f18d5c86.png">

Specifically, it seems that if my mouse is over the text, then it doesn't work. If I move the mouse so that it is still within the button but NOT over the text, then the button is clickable.

**Comment by nickykrause** [comment]
FYI: This came up again in testing last Friday

**Comment by jenniferthibault** [comment]
This gets me all the time. :shakes-fist:

**Comment by nickykrause** [comment]
This doesn't seem to be an issue anymore. @noahmanger -- was this actively fixed at some point, as a part of some recent release?

**Comment by patphongs** [comment]
Issue moved to [18F/fec-cms #1254](https://github.com/18F/fec-cms/issues/1254) via [**ZenHub**](https://www.zenhub.com/)
