### ISSUE TITLE
Users struggle to find individual contributions via the main navigation menu

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#62]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-05-12.md), one user struggled to find how she could search `Individual contributions.` 

Specifically, she was answering this question: _If you wanted to know who one of your neighbors or family members (or any specific person) donated money to in the last presidential election, what would you do to find out?_

Her first instinct was to go to the Campaign finance data menu, but she didn't see something there that she liked. While she was clicking around, she said _"I am just looking for the word `individual`..."_

Eventually, she scrolled down on the homepage and saw the word "individual" in the Campaign finance data section.  

The menu:
<img width="1258" alt="screen shot 2017-05-16 at 10 31 18 am" src="https://cloud.githubusercontent.com/assets/1450173/26114423/d65e16d8-3a22-11e7-8ba9-dc32903f48b5.png">

**Comment by nickykrause** [comment]
We tested this again last week. Two of the three participants again struggled to find Individual Contributions, which suggests that this is indeed a problem. For both of the two users who struggled, their inclination was to go to the CFD menu, but they didn't see anything there that seemed relevant to them. 

In both cases, they said they were looking for something like "Individual" or "Donor history"

**Comment by noahmanger** [comment]
This is something I'd like to move on sooner than later. Can you start doing some thinking around solutions?

**Comment by nickykrause** [comment]
Sure @noahmanger . Should we move this one into one of the other repos? I'm happy to move it and assign myself (which repo makes the most sense?). I can take a look at it this week.

**Comment by noahmanger** [comment]
Go for it!

**Comment by nickykrause** [comment]
Issue moved to [18F/openFEC-web-app #2061](https://github.com/18F/openFEC-web-app/issues/2061) via [**ZenHub**](https://www.zenhub.com/)
