### ISSUE TITLE
The H4CC menu may alienate users who are not candidates/committees, but who could benefit from info there

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#70]
This is a bit vague, but it is a trend that is emerging in some of the usability tests, so I wanted to track it somewhere.

Essentially, there are some users who are _not_ candidates or committees who are looking for guidance about compliance, training, or "the rules," but who apparently do not feel that the `Help for candidates and committees` section is meant for them (possibly due to its title). This is unfortunate because the answers they might be looking for often live in that section.

For example, in an open-ended usability testing this week, a PhD candidate doing campaign finance research mentioned that she sometimes comes to the FEC site looking for information about trainings, even though those trainings are not typically targeted to her. When asked to try to complete that task on the new site, she struggled to find information about training, even though it appears prominently in the H4CC menu (which she never thought to open): 
<img width="1263" alt="screen shot 2017-05-26 at 11 22 16 am" src="https://cloud.githubusercontent.com/assets/1450173/26503264/9dfcbb60-4205-11e7-938e-475ec904ac02.png">

Another possible example of this issues comes from the following feedback submission: https://github.com/18F/FEC/issues/4099, where the user notes that it was difficult to find the `contribution limits` chart:
> It took me three (counterintuitive) steps to find the contribution limits chart. Really? Please make it easier for folks who aren't candidates/committees to find from the main page.

Since we did not observe this user's process, it is hard to say if the problem is related, but it is worth noting that her comment suggests candidates/committees are perceived to be higher priority than other groups.

---

## Big picture
To me, the big picture question here seems to be whether or not having an audience-based top-level navigation structure is really working for us. We have encountered this design question repeatedly (e.g., when designing the homepage and the H4CC section), and we have waffled back and forth a bit in answering it. In the past, we acknowledged that _on some level_, it is true that the FEC has specialized user groups who need audience-specific info, but we have also noted that it is not best practice to fundamentally organize content by user group, since it can have the alienating effects that we are seeing traces of here.

**Comment by patphongs** [comment]
This issue has been worked on and a new Help for candidates and committees strategy and design has been made and will be implemented in sprint 3.6. https://github.com/18F/openFEC-web-app/issues/2287
