### ISSUE TITLE
Test help for candidates and committees menu

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#73]
[This issue](https://github.com/18F/fec-testing/issues/67) revealed that our previous `help for candidates and committees` menu was not making it clear enough that the section contained guidance for committees. The [new homepage designs](https://github.com/18F/openFEC-web-app/issues/2159) include a change to the main nav, which we think should help.

We can test:
Do people click "Campaign guidance" in the help for candidates and committees menu?

**Comment by patphongs** [comment]
This was tested during the 2017 Chicago conference and users were able to successfully click on the `Campaign guidance`link in the H4CC menu to access this information.
