### ISSUE TITLE
Users need clarification about "other" category on the Campaign Finance Data landing page graphs.

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-testing#8]
**from test script:**
https://github.com/18F/FEC/blob/master/test_scripts/2016-08-18.md

**feature tested:** 
Campaign finance data landing page graphs

**original question:**
After looking at this graph, are you curious about anything or have any questions in your mind about campaign finance fundraising?

**synthesized answer:**
Again, requests were all over the place. It's worth noting is that all the areas of interest that users brought up were diving deeper into the data— going from this broad view to more breakdowns and comparisons, whether that be between parties or candidates or spending types. 

_One user wanted to know what "other" was comprised of. We've heard this before._

**action:**
Users need clarification about "other" category on the Campaign Finance Data landing page graphs.

**Comment by emileighoutlaw** [comment]
Ah! We have an issue for this already in progress: https://github.com/18F/fec-cms/issues/523#issuecomment-250481532

But my brain is Friday-ed, and I can't remember how we link usability finding issues to existing issues.

**Comment by nickykrause** [comment]
Closing in favor of https://github.com/18F/fec-cms/issues/523#issuecomment-250481532
