### ISSUE TITLE
Test new designs for Help for candidates and committees landing

### ISSUE THREAD

**Issue by patphongs** [18F/fec-testing#92]
During the November FEC conference, we need to test the new designs that will be merged into the FEC's dev site. 

Completion Criteria:
- [ ] Discuss what we want to learn from these new designs
- [ ] Identify the top tasks that users need to accomplish in this section
- [ ] Write user test script. May want to design script to be a mini test for easy testing on-the-spot testing at conference.

**Let's slate this for Sprint 4.3**

**Comment by JonellaCulmer** [comment]
This was tested at the DC Conference. Relevant issues resulting from this testing has been logged and closing this issue in favor of those new issues, specifically #96.
